import { GoodsList } from "src/app/interfaces/product";

// generated by json-generator.com
export const list: GoodsList = [
  {
    "id": "63e4fd95e3d154adaf51567e",
    "name": "Futurize",
    "description": "Commodo fugiat anim commodo tempor veniam tempor amet ut commodo aute nostrud nulla consectetur."
  },
  {
    "id": "63e4fd95c8bcb73587a6804f",
    "name": "Limozen",
    "description": "In dolor qui tempor laboris ipsum est nulla proident."
  },
  {
    "id": "63e4fd95a0de27c77d2b29df",
    "name": "Wrapture",
    "description": "Consectetur nulla sit ipsum ex eu eiusmod laboris labore occaecat aliqua aute ad."
  },
  {
    "id": "63e4fd95418d58c75799ff83",
    "name": "Exiand",
    "description": "Nulla quis minim et nulla consectetur laborum."
  },
  {
    "id": "63e4fd95c5e5425a2b70cfca",
    "name": "Elita",
    "description": "Adipisicing veniam do ex laboris pariatur nisi eiusmod sunt quis velit proident."
  },
  {
    "id": "63e4fd951b86d19afd94f85f",
    "name": "Thredz",
    "description": "Nostrud culpa Lorem dolor sint deserunt nulla non ullamco proident dolor incididunt dolor duis dolor."
  },
  {
    "id": "63e4fd952b11db7f3b7e6a94",
    "name": "Progenex",
    "description": "Exercitation do cupidatat voluptate quis non eiusmod."
  },
  {
    "id": "63e4fd952440a8d1dc250644",
    "name": "Housedown",
    "description": "Cupidatat elit in eiusmod est consequat non Lorem excepteur consectetur incididunt quis laboris reprehenderit fugiat."
  },
  {
    "id": "63e4fd95f244e2b9f5478e3a",
    "name": "Magnina",
    "description": "Veniam enim veniam dolor eiusmod cillum."
  },
  {
    "id": "63e4fd95d24f9a6dab8e39f1",
    "name": "Zanymax",
    "description": "Mollit nulla culpa in in velit esse fugiat."
  },
  {
    "id": "63e4fd9533d6556ea80906e5",
    "name": "Medcom",
    "description": "Voluptate irure excepteur nulla culpa occaecat ex duis sit."
  },
  {
    "id": "63e4fd95343c818c7c67d081",
    "name": "Caxt",
    "description": "Do qui ex velit reprehenderit."
  },
  {
    "id": "63e4fd95f9e3d034bafe1e20",
    "name": "Virxo",
    "description": "Aute mollit ex voluptate exercitation esse elit non ut id do."
  },
  {
    "id": "63e4fd952f81852311163076",
    "name": "Biflex",
    "description": "Duis deserunt mollit sint ad culpa duis nulla mollit nostrud commodo."
  },
  {
    "id": "63e4fd95b07613cb63110426",
    "name": "Exospeed",
    "description": "Nisi Lorem esse ut non tempor proident excepteur nulla incididunt irure."
  },
  {
    "id": "63e4fd95ffc67d5890966bab",
    "name": "Tubesys",
    "description": "Exercitation id ad aliqua proident sit reprehenderit irure aute ipsum aliqua sit nulla minim sit."
  },
  {
    "id": "63e4fd95e8709f86f1c3bb34",
    "name": "Signidyne",
    "description": "Irure eu dolor id sit labore."
  },
  {
    "id": "63e4fd953d1bdfe6166ad09a",
    "name": "Lunchpad",
    "description": "Reprehenderit ullamco velit occaecat cillum nulla pariatur."
  },
  {
    "id": "63e4fd953c5d224924a1dcd6",
    "name": "Zerbina",
    "description": "Ad nostrud sit cupidatat id ea aliqua aliqua reprehenderit."
  },
  {
    "id": "63e4fd95e75b0727e1ee625d",
    "name": "Crustatia",
    "description": "Nisi magna consectetur mollit mollit sit eu cillum anim occaecat proident consectetur deserunt dolore aute."
  }
]
